import os
import traceback
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

import msal
import psycopg2
import requests
from flask import Flask, jsonify, render_template, request
from openpyxl import Workbook

# -----------------------------
# Local storage
# -----------------------------
# NOTE: /tmp is temporary. Fine for generated Excel cache,
# but DB is now the real source of truth.
BASE_DIR = Path("/tmp")
DATA_DIR = BASE_DIR / "data"
EXCEL_FILE_PATH = DATA_DIR / "pe_form_data.xlsx"

HEADERS = [
    "S.No",
    "PE / Non-PE",
    "Category",
    "Executor",
    "Total Node Count",
    "Site / Cell",
    "Circle",
    "Date of PE",
    "PE Purpose",
    "PE Purpose - Sub2",
    "Activity Initiator",
    "Activity Owner",
    "Activity Executor",
    "Deploy Approval",
    "NPO KPI Approval",
    "NPO AT Approval",
    "TSS Approval",
    "Status",
    "Domain",
    "Remarks1",
    "Remarks2",
    "Remarks",
    "Created At (UTC)",
]

# -----------------------------
# Flask app
# -----------------------------
app = Flask(__name__, template_folder="templates", static_folder="static")

# -----------------------------
# Azure / Graph Config
# -----------------------------
CLIENT_ID = os.getenv("CLIENT_ID", "").strip()
TENANT_ID = os.getenv("TENANT_ID", "").strip()
CLIENT_SECRET = os.getenv("CLIENT_SECRET", "").strip()

ONEDRIVE_USER = os.getenv("ONEDRIVE_USER", "").strip()
ONEDRIVE_FOLDER = os.getenv("ONEDRIVE_FOLDER", "Rudra/PEData").strip().strip("/")

AUTHORITY = f"https://login.microsoftonline.com/{TENANT_ID}"
SCOPES = ["https://graph.microsoft.com/.default"]

# -----------------------------
# Database Config
# IMPORTANT: Set via environment variable
# Example:
# DATABASE_URL=postgresql://user:password@host/dbname?sslmode=require
# -----------------------------
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()


# -----------------------------
# Helpers
# -----------------------------
def validate_graph_config() -> None:
    missing = []
    if not CLIENT_ID:
        missing.append("CLIENT_ID")
    if not TENANT_ID:
        missing.append("TENANT_ID")
    if not CLIENT_SECRET:
        missing.append("CLIENT_SECRET")
    if not ONEDRIVE_USER:
        missing.append("ONEDRIVE_USER")

    if missing:
        raise RuntimeError(
            "Missing required Graph environment variables: " + ", ".join(missing)
        )


def validate_db_config() -> None:
    if not DATABASE_URL:
        raise RuntimeError("Missing required environment variable: DATABASE_URL")


def normalized_database_url() -> str:
    """
    Add sslmode=require if not present.
    Useful for many managed PostgreSQL services.
    """
    validate_db_config()

    if "sslmode=" in DATABASE_URL:
        return DATABASE_URL

    separator = "&" if "?" in DATABASE_URL else "?"
    return DATABASE_URL + f"{separator}sslmode=require"


def get_db_connection():
    return psycopg2.connect(normalized_database_url())


def ensure_workbook_dir() -> None:
    EXCEL_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)


def list_to_string(value):
    if isinstance(value, list):
        return ", ".join(str(item).strip() for item in value if str(item).strip())
    if value is None:
        return ""
    return str(value).strip()


def ensure_database() -> None:
    """
    Create sequence + table if not present.
    sno is generated by database sequence to avoid duplicate numbers.
    """
    with get_db_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE SEQUENCE IF NOT EXISTS pe_form_data_sno_seq START 1;
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS pe_form_data (
                    id BIGSERIAL PRIMARY KEY,
                    sno BIGINT NOT NULL UNIQUE DEFAULT nextval('pe_form_data_sno_seq'),
                    pe_non_pe TEXT NOT NULL,
                    category TEXT NOT NULL,
                    executor TEXT NOT NULL,
                    total_node_count TEXT,
                    site_cell TEXT NOT NULL,
                    circle TEXT,
                    date_of_pe TEXT,
                    pe_purpose TEXT,
                    pe_purpose_sub2 TEXT,
                    activity_initiator TEXT,
                    activity_owner TEXT,
                    activity_executor TEXT,
                    deploy_approval TEXT,
                    npo_kpi_approval TEXT,
                    npo_at_approval TEXT,
                    tss_approval TEXT,
                    status TEXT,
                    domain TEXT,
                    remarks1 TEXT,
                    remarks2 TEXT,
                    remarks TEXT,
                    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """)

            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_pe_form_data_created_at
                ON pe_form_data (created_at_utc DESC);
            """)

        conn.commit()


def get_next_sno() -> int:
    """
    Read next value from DB sequence WITHOUT consuming it.
    Better than Excel row count.
    """
    ensure_database()

    with get_db_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT last_value, is_called
                FROM pe_form_data_sno_seq
            """)
            last_value, is_called = cursor.fetchone()

            if is_called:
                return int(last_value) + 1
            return int(last_value)


def save_row_to_db(data: dict) -> dict:
    """
    Save submitted form data to PostgreSQL.
    DB assigns S.No automatically via sequence.
    Returns inserted sno + created_at.
    """
    ensure_database()

    with get_db_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                INSERT INTO pe_form_data (
                    pe_non_pe,
                    category,
                    executor,
                    total_node_count,
                    site_cell,
                    circle,
                    date_of_pe,
                    pe_purpose,
                    pe_purpose_sub2,
                    activity_initiator,
                    activity_owner,
                    activity_executor,
                    deploy_approval,
                    npo_kpi_approval,
                    npo_at_approval,
                    tss_approval,
                    status,
                    domain,
                    remarks1,
                    remarks2,
                    remarks
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING sno, created_at_utc
            """, (
                list_to_string(data.get("peNonPe")),
                list_to_string(data.get("category")),
                list_to_string(data.get("executor")),
                str(data.get("totalNodeCount", "")).strip(),
                list_to_string(data.get("siteCell")),
                list_to_string(data.get("circle")),
                str(data.get("dateOfPe", "")).strip(),
                list_to_string(data.get("pePurpose")),
                list_to_string(data.get("pePurposeSub2")),
                list_to_string(data.get("activityInitiator")),
                list_to_string(data.get("activityOwner")),
                list_to_string(data.get("activityExecutor")),
                list_to_string(data.get("deployApproval")),
                list_to_string(data.get("npoKpiApproval")),
                list_to_string(data.get("npoAtApproval")),
                list_to_string(data.get("tssApproval")),
                list_to_string(data.get("status")),
                list_to_string(data.get("domain")),
                list_to_string(data.get("remarks1")),
                list_to_string(data.get("remarks2")),
                str(data.get("remarks", "")).strip(),
            ))

            sno, created_at_utc = cursor.fetchone()

        conn.commit()

    return {
        "sno": int(sno),
        "created_at_utc": created_at_utc.isoformat() if created_at_utc else None
    }


def export_db_to_excel() -> None:
    """
    Rebuild Excel from PostgreSQL so Excel always mirrors DB.
    """
    ensure_database()
    ensure_workbook_dir()

    with get_db_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT
                    sno,
                    pe_non_pe,
                    category,
                    executor,
                    total_node_count,
                    site_cell,
                    circle,
                    date_of_pe,
                    pe_purpose,
                    pe_purpose_sub2,
                    activity_initiator,
                    activity_owner,
                    activity_executor,
                    deploy_approval,
                    npo_kpi_approval,
                    npo_at_approval,
                    tss_approval,
                    status,
                    domain,
                    remarks1,
                    remarks2,
                    remarks,
                    TO_CHAR(created_at_utc AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
                FROM pe_form_data
                ORDER BY sno ASC
            """)
            rows = cursor.fetchall()

    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "PE Data"
    worksheet.append(HEADERS)

    for row in rows:
        worksheet.append(list(row))

    workbook.save(EXCEL_FILE_PATH)
    workbook.close()


def get_graph_token() -> str:
    """
    Acquire app-only token using client credentials flow.
    """
    validate_graph_config()

    app_msal = msal.ConfidentialClientApplication(
        CLIENT_ID,
        authority=AUTHORITY,
        client_credential=CLIENT_SECRET,
    )

    result = app_msal.acquire_token_for_client(scopes=SCOPES)

    if "access_token" not in result:
        raise RuntimeError(
            "OneDrive token error: "
            f"error={result.get('error')} | "
            f"description={result.get('error_description')} | "
            f"correlation_id={result.get('correlation_id')}"
        )

    return result["access_token"]


def graph_request(method: str, url: str, token: str, **kwargs):
    headers = kwargs.pop("headers", {})
    headers.update({
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
    })

    response = requests.request(method, url, headers=headers, timeout=60, **kwargs)
    return response


def ensure_onedrive_folder(token: str, folder_path: str) -> None:
    """
    Ensures nested folder path exists in target user's OneDrive.
    Example folder_path: Rudra/PEData
    """
    if not folder_path:
        return

    parts = [p.strip() for p in folder_path.split("/") if p.strip()]
    current_path = ""

    for part in parts:
        next_path = f"{current_path}/{part}" if current_path else part

        check_url = (
            f"https://graph.microsoft.com/v1.0/users/{quote(ONEDRIVE_USER, safe='')}"
            f"/drive/root:/{quote(next_path, safe='/')}"
        )
        check_resp = graph_request("GET", check_url, token)

        if check_resp.status_code == 200:
            current_path = next_path
            continue

        if check_resp.status_code != 404:
            try:
                err_json = check_resp.json()
            except Exception:
                err_json = check_resp.text
            raise RuntimeError(f"Folder check failed for '{next_path}': {err_json}")

        # Create missing folder
        if current_path:
            create_url = (
                f"https://graph.microsoft.com/v1.0/users/{quote(ONEDRIVE_USER, safe='')}"
                f"/drive/root:/{quote(current_path, safe='/')}:/children"
            )
        else:
            create_url = (
                f"https://graph.microsoft.com/v1.0/users/{quote(ONEDRIVE_USER, safe='')}"
                f"/drive/root/children"
            )

        create_body = {
            "name": part,
            "folder": {},
            "@microsoft.graph.conflictBehavior": "replace"
        }

        create_resp = graph_request("POST", create_url, token, json=create_body)

        if create_resp.status_code not in (200, 201):
            try:
                err_json = create_resp.json()
            except Exception:
                err_json = create_resp.text
            raise RuntimeError(f"Folder create failed for '{next_path}': {err_json}")

        current_path = next_path


def upload_to_onedrive() -> dict:
    """
    Upload local Excel file to target user's OneDrive folder.
    Returns uploaded item details.
    """
    if not EXCEL_FILE_PATH.exists():
        raise RuntimeError("Local Excel file not found for upload.")

    token = get_graph_token()

    # Ensure target folder exists
    ensure_onedrive_folder(token, ONEDRIVE_FOLDER)

    relative_path = (
        f"{ONEDRIVE_FOLDER}/{EXCEL_FILE_PATH.name}"
        if ONEDRIVE_FOLDER else EXCEL_FILE_PATH.name
    )

    upload_url = (
        f"https://graph.microsoft.com/v1.0/users/{quote(ONEDRIVE_USER, safe='')}"
        f"/drive/root:/{quote(relative_path, safe='/')}:/content"
    )

    with open(EXCEL_FILE_PATH, "rb") as f:
        response = graph_request(
            "PUT",
            upload_url,
            token,
            headers={"Content-Type": "application/octet-stream"},
            data=f,
        )

    if response.status_code not in (200, 201):
        try:
            err_json = response.json()
        except Exception:
            err_json = response.text
        raise RuntimeError(f"OneDrive upload failed: {err_json}")

    item = response.json()

    return {
        "id": item.get("id"),
        "name": item.get("name"),
        "web_url": item.get("webUrl"),
        "size": item.get("size"),
    }


def validate_payload(data: dict):
    required_single = {
        "peNonPe": "PE / Non-PE",
        "category": "Category",
        "executor": "Executor",
        "siteCell": "Site / Cell",
    }

    # NOTE:
    # sno is NOT validated anymore.
    # DB generates it automatically.

    for key, label in required_single.items():
        value = data.get(key, [])
        if isinstance(value, list):
            if not value:
                return f"{label} select karein."
        elif not str(value).strip():
            return f"{label} select karein."

    return None


# -----------------------------
# Routes
# -----------------------------
@app.get("/")
def home():
    ensure_database()
    ensure_workbook_dir()
    return render_template("Form.html")


@app.get("/health")
def health():
    try:
        validate_db_config()
        validate_graph_config()
        ensure_database()
        ensure_workbook_dir()

        return jsonify({
            "status": "ok",
            "database": "connected-config-present",
            "local_excel": str(EXCEL_FILE_PATH),
            "onedrive_user": ONEDRIVE_USER,
            "onedrive_folder": ONEDRIVE_FOLDER,
        })
    except Exception as exc:
        return jsonify({"status": "error", "message": str(exc)}), 500


@app.get("/next-sno")
def next_sno():
    try:
        return jsonify({"next_sno": get_next_sno()})
    except Exception as exc:
        print("ERROR in /next-sno:", exc)
        traceback.print_exc()
        return jsonify({"next_sno": "", "error": str(exc)}), 500


@app.post("/submit")
def submit():
    try:
        data = request.get_json(force=True) or {}

        error_message = validate_payload(data)
        if error_message:
            return jsonify({"success": False, "message": error_message}), 400

        # Step 1: Save into PostgreSQL
        inserted = save_row_to_db(data)

        # Step 2: Rebuild Excel from DB
        export_db_to_excel()

        # Step 3: Upload Excel to OneDrive
        try:
            uploaded = upload_to_onedrive()
            return jsonify({
                "success": True,
                "message": "Data PostgreSQL me save ho gaya, Excel generate ho gayi, aur OneDrive pe upload bhi ho gaya.",
                "assigned_sno": inserted["sno"],
                "created_at_utc": inserted["created_at_utc"],
                "local_excel": str(EXCEL_FILE_PATH),
                "onedrive_file": uploaded,
            })
        except Exception as upload_exc:
            print("ERROR in OneDrive upload:", upload_exc)
            traceback.print_exc()

            return jsonify({
                "success": False,
                "saved_in_db": True,
                "excel_generated": True,
                "message": "Data PostgreSQL me save ho gaya aur Excel generate ho gayi, lekin OneDrive upload fail ho gaya.",
                "assigned_sno": inserted["sno"],
                "created_at_utc": inserted["created_at_utc"],
                "local_excel": str(EXCEL_FILE_PATH),
                "upload_error": str(upload_exc),
            }), 502

    except Exception as exc:
        print("ERROR in /submit:", exc)
        traceback.print_exc()
        return jsonify({"success": False, "message": str(exc)}), 500


if __name__ == "__main__":
    ensure_database()
    ensure_workbook_dir()
    port = int(os.environ.get("PORT", 8000))
    app.run(host="0.0.0.0", port=port, debug=False)
