
services:
  - type: web
    name: pe-form-app
    runtime: python
    plan: starter
    autoDeployTrigger: commit

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 600 main_form_fixed:app

    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        value: postgresql://form_excel_data_user:YOUR_PASSWORD@dpg-d8ji2grbc2fs73bnofug-a/form_excel_data
      - key: PYTHONUNBUFFERED
        value: "1"


